import {NextResponse} from 'next/server';
import {z} from 'zod';
const Character=z.object({id:z.string(),name:z.string().min(1),role:z.string().optional(),appearance:z.string().min(1),wardrobe:z.string().optional(),voice:z.string().optional(),personality:z.string().optional(),relationships:z.string().optional()});
const Memory=z.object({episodeNumber:z.number(),summary:z.string(),continuityNotes:z.string().optional()});
const S=z.object({prompt:z.string().min(3),minutes:z.number().min(0.5).max(20),mode:z.enum(['education','series']).default('education'),seriesTitle:z.string().optional(),episodeNumber:z.number().int().min(1).optional(),characters:z.array(Character).default([]),episodeMemory:z.array(Memory).default([])});
function sentences(text:string){return text.replace(/\s+/g,' ').split(/(?<=[.!?؟؛])\s+|\n+/).map(x=>x.trim()).filter(Boolean)}
function chunks(parts:string[],count:number){const out:string[]=[];const size=Math.max(1,Math.ceil(parts.length/count));for(let i=0;i<parts.length;i+=size)out.push(parts.slice(i,i+size).join(' '));return out}
function durations(total:number,count:number){const base=Math.max(10,Math.min(60,Math.round(total/count)));const values=Array.from({length:count},()=>base);let diff=total-values.reduce((a,b)=>a+b,0),i=0;while(diff!==0&&i<10000){const k=i%count;if(diff>0&&values[k]<60){values[k]++;diff--}else if(diff<0&&values[k]>10){values[k]--;diff++}i++}return values}
export async function POST(req:Request){try{const x=S.parse(await req.json()),totalSeconds=Math.round(x.minutes*60),target=Math.max(1,Math.round(totalSeconds/30)),source=sentences(x.prompt),beats=chunks(source,target),count=Math.max(1,Math.min(beats.length,Math.floor(totalSeconds/10))),selected=beats.slice(0,count),timing=durations(totalSeconds,count);
const bible=x.characters.map(c=>[c.name,c.role&&('role: '+c.role),'appearance: '+c.appearance,c.wardrobe&&('wardrobe: '+c.wardrobe),c.voice&&('voice: '+c.voice),c.personality&&('personality: '+c.personality),c.relationships&&('relationships: '+c.relationships)].filter(Boolean).join(' | ')).join('\n');
const memory=x.episodeMemory.slice(-5).map(m=>'Episode '+m.episodeNumber+': '+m.summary+(m.continuityNotes?' | continuity: '+m.continuityNotes:'')).join('\n');
const continuity='LOCK CONTINUITY: recurring characters must retain the same facial identity, age, body proportions, voice identity and established wardrobe. Never redesign, replace or merge recurring characters.';
const education='EDUCATIONAL FIDELITY: preserve the supplied educational content and meaning exactly. Do not add unsupported facts, change claims, or replace the source.';
const scenes=selected.map((beat,i)=>{const prompt=[x.mode==='education'?education:continuity,x.mode==='series'&&bible?'CHARACTER BIBLE — authoritative identity reference:\n'+bible:'',x.mode==='series'&&memory?'PREVIOUS EPISODE MEMORY:\n'+memory:'','SOURCE / STORY CONTEXT: '+x.prompt,'CURRENT SCENE CONTENT: '+beat,i>0?'PREVIOUS SCENE: '+selected[i-1]:'',x.mode==='series'?'Continue established story state and relationships. Use only the Character Bible identity for recurring characters.':'Design visuals that directly support the educational content.','Cinematic composition, natural motion, clear subject action, no logos.'].filter(Boolean).join('\n');return{id:crypto.randomUUID(),title:(x.mode==='education'?'Learning Scene ':'Episode Scene ')+(i+1),sourceText:beat,prompt,duration:timing[i],status:'planned' as const}});
return NextResponse.json({id:crypto.randomUUID(),title:x.prompt.slice(0,55),prompt:x.prompt,mode:x.mode,seriesTitle:x.seriesTitle,episodeNumber:x.episodeNumber,characters:x.characters,episodeMemory:x.episodeMemory,minutes:x.minutes,totalSeconds,createdAt:new Date().toISOString(),scenes})}catch(e){return NextResponse.json({error:e instanceof Error?e.message:'Planning failed'},{status:400})}}