'use client';
import {useState} from 'react';
import Link from 'next/link';
import {saveProject,VideoProject} from '@/lib/project-store';
import GenerationPanel from '@/components/GenerationPanel';
import SystemStatus from '@/components/SystemStatus';
import FullVideoGenerator from '@/components/FullVideoGenerator';

type Mode='education'|'series';

export default function Home(){
 const[mode,setMode]=useState<Mode>('education');
 const[prompt,setPrompt]=useState('');const[minutes,setMinutes]=useState(5);const[plan,setPlan]=useState<VideoProject|null>(null);const[busy,setBusy]=useState(false);const[selected,setSelected]=useState(0);
 async function generate(){if(!prompt.trim())return;setBusy(true);try{const r=await fetch('/api/script',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt,minutes,mode})});const data=await r.json();if(!r.ok)throw new Error(data.error||'Planning failed');setPlan(data);setSelected(0);saveProject(data)}finally{setBusy(false)}}
 const scene=plan?.scenes?.[selected];
 return <main className="min-h-screen"><header className="border-b border-white/10 px-6 py-4"><b className="text-xl">AI Video Studio</b><span className="ml-3 text-sm text-purple-400">Education + Series Production</span><div className="float-right flex items-center gap-5"><SystemStatus/><Link href="/studio" className="text-sm text-purple-300">Production Studio</Link><Link href="/projects" className="text-sm text-slate-300 hover:text-white">My Projects →</Link></div></header>
 <div className="mx-auto max-w-7xl p-6">
  <div className="mb-6 grid gap-4 md:grid-cols-2">
   <button onClick={()=>{setMode('education');setPlan(null)}} className={'card p-6 text-left border '+(mode==='education'?'border-purple-500 bg-purple-500/10':'border-white/10')}><span className="text-3xl">🎓</span><h2 className="mt-3 text-xl font-bold">Educational Studio</h2><p className="mt-2 text-sm text-slate-400">Paste the educational text exactly as written. AI preserves the content and turns it into visual scenes, narration and a complete video.</p></button>
   <button onClick={()=>{setMode('series');setPlan(null)}} className={'card p-6 text-left border '+(mode==='series'?'border-purple-500 bg-purple-500/10':'border-white/10')}><span className="text-3xl">🎬</span><h2 className="mt-3 text-xl font-bold">Series Studio</h2><p className="mt-2 text-sm text-slate-400">Create episodes from a script or idea with persistent characters, visual continuity and connected scenes across the series.</p></button>
  </div>
  <div className="grid gap-6 lg:grid-cols-[1fr_340px]"><section><div className="card p-6"><p className="text-sm text-purple-400">{mode==='education'?'EDUCATIONAL DIRECTOR':'EPISODE DIRECTOR'}</p><h1 className="mt-2 text-3xl font-bold">{mode==='education'?'Turn your text into a visual lesson':'Build a complete connected episode'}</h1><p className="mt-3 text-slate-400">{mode==='education'?'The original educational meaning is preserved while AI designs the scenes.':'Characters and story continuity are carried through every scene and future episode.'}</p><textarea value={prompt} onChange={e=>setPrompt(e.target.value)} className="mt-6 min-h-48 w-full rounded-xl border border-white/10 bg-black/20 p-4 outline-none" placeholder={mode==='education'?'Paste the educational text here…':'Paste an episode script or describe the episode idea…'}/><div className="mt-4 flex flex-wrap gap-3"><select value={minutes} onChange={e=>setMinutes(Number(e.target.value))} className="ghost btn"><option value={1}>1 minute</option><option value={3}>3 minutes</option><option value={5}>5 minutes</option><option value={10}>10 minutes</option><option value={15}>15 minutes</option><option value={20}>20 minutes</option></select><button onClick={generate} className="btn primary" disabled={busy}>{busy?'Directing…':mode==='education'?'Create educational storyboard':'Create episode storyboard'}</button></div></div>
  {plan&&<><div className="card mt-5 p-5"><div className="flex items-center justify-between"><h2 className="text-xl font-bold">{mode==='education'?'Lesson storyboard':'Episode storyboard'} · {plan.scenes.length} scenes · {Math.round(plan.minutes*60)} sec</h2><span className="text-xs text-slate-500">10–60 sec scenes based on content</span></div><div className="mt-4 grid gap-3 sm:grid-cols-2">{plan.scenes.map((s,i:number)=><button onClick={()=>setSelected(i)} key={s.id} className={'rounded-xl border p-4 text-left '+(selected===i?'border-purple-500 bg-purple-500/10':'border-white/10')}><b>{i+1}. {s.title}</b><p className="mt-1 text-xs text-slate-500">{s.duration}s · {s.status}</p><p className="mt-2 line-clamp-2 text-xs text-slate-400">{s.sourceText||s.prompt}</p></button>)}</div></div><GenerationPanel prompt={scene?.prompt ?? plan.prompt ?? ''} duration={scene?.duration ?? 10}/><FullVideoGenerator scenes={plan.scenes}/></>}</section>
  <aside className="space-y-4"><div className="card p-5"><h2 className="font-bold">{mode==='education'?'Educational rules':'Series continuity'}</h2>{mode==='education'?<p className="mt-3 text-sm text-slate-400">Keep the supplied text and its meaning intact. The director may split, visualize and pace it, but must not invent facts.</p>:<><p className="mt-3 text-sm text-slate-400">Character identity is locked into every scene prompt. Character Library and episode-to-episode continuity are the next production layer.</p><div className="mt-4 rounded-xl border border-white/10 p-3 text-xs text-slate-400">Character Bible · voice · appearance · wardrobe · relationships · episode memory</div></>} </div><div className="card p-5"><h2 className="font-bold">Scene timing</h2><p className="mt-3 text-sm text-slate-400">The director chooses scene length from 10 to 60 seconds according to the amount of dialogue, narration and action, then the clips are assembled into the complete video.</p><Link href="/studio" className="btn primary mt-4 block text-center">Open Production Studio</Link></div></aside></div>
 </div></main>
}