'use client';
import {useState} from 'react';
import {videoTools} from '@/lib/video-tools';
import Link from 'next/link';
import {saveProject} from '@/lib/project-store';
import GenerationPanel from '@/components/GenerationPanel';
import SystemStatus from '@/components/SystemStatus';

export default function Home(){
 const[prompt,setPrompt]=useState('');const[minutes,setMinutes]=useState(1);const[plan,setPlan]=useState<any>(null);const[busy,setBusy]=useState(false);const[selected,setSelected]=useState(0);
 async function generate(){if(!prompt.trim())return;setBusy(true);const r=await fetch('/api/script',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt,minutes})});const data=await r.json();setPlan(data);setSelected(0);saveProject(data);setBusy(false)}
 const scene=plan?.scenes?.[selected];
 return <main className="min-h-screen"><header className="border-b border-white/10 px-6 py-4"><b className="text-xl">AI Video Studio</b><span className="ml-3 text-sm text-purple-400">Open-source AI creation</span><div className="float-right flex items-center gap-5"><SystemStatus/><Link href="/studio" className="text-sm text-purple-300">Production Studio</Link><Link href="/projects" className="text-sm text-slate-300 hover:text-white">My Projects →</Link></div></header>
 <div className="mx-auto grid max-w-7xl gap-6 p-6 lg:grid-cols-[240px_1fr_340px]"><aside className="card p-3"><p className="mb-3 px-2 text-xs uppercase text-slate-500">Create</p>{videoTools.map((t,i)=><button key={t.id} className={"mb-2 w-full rounded-xl p-3 text-left "+(i===0?'bg-purple-600/20 text-purple-300':'hover:bg-white/5')}><b className="block text-sm">{t.name}</b><span className="text-xs text-slate-500">{t.engine}</span></button>)}</aside>
 <section><div className="card p-6"><p className="text-sm text-purple-400">AI VIDEO DIRECTOR</p><h1 className="mt-2 text-4xl font-bold">Turn an idea into a complete video</h1><p className="mt-3 text-slate-400">Idea → script → scenes → GPU generation → MP4.</p><textarea value={prompt} onChange={e=>setPrompt(e.target.value)} className="mt-6 min-h-36 w-full rounded-xl border border-white/10 bg-black/20 p-4 outline-none" placeholder="Describe the video you want to create…"/><div className="mt-4 flex flex-wrap gap-3"><select value={minutes} onChange={e=>setMinutes(Number(e.target.value))} className="ghost btn"><option value={1}>1 minute</option><option value={5}>5 minutes</option><option value={10}>10 minutes</option><option value={20}>20 minutes</option></select><button onClick={generate} className="btn primary">{busy?'Planning…':'Create storyboard'}</button></div></div>
 {plan&&<><div className="card mt-5 p-5"><div className="flex items-center justify-between"><h2 className="text-xl font-bold">Storyboard · {plan.scenes.length} scenes</h2><span className="text-xs text-slate-500">Select a scene to generate</span></div><div className="mt-4 grid gap-3 sm:grid-cols-2">{plan.scenes.map((s:any,i:number)=><button onClick={()=>setSelected(i)} key={s.id} className={"rounded-xl border p-4 text-left "+(selected===i?'border-purple-500 bg-purple-500/10':'border-white/10')}><b>{i+1}. {s.title}</b><p className="mt-1 text-xs text-slate-500">{s.duration}s · {s.status}</p><p className="mt-2 line-clamp-2 text-xs text-slate-400">{s.prompt}</p></button>)}</div></div><div className="card mt-5 p-5"><p className="text-sm font-semibold">Visual generation</p><p className="mt-2 text-sm text-slate-400">Your storyboard is ready. Choose a scene above, then generate its real MP4 clip with LTX.</p></div><GenerationPanel prompt={scene?.prompt||plan.prompt}/></>}</section>
 <aside className="space-y-4"><div className="card p-5"><h2 className="font-bold">Video settings</h2><label className="mt-4 block text-xs text-slate-500">Resolution</label><select className="ghost mt-1 w-full rounded-xl p-3"><option>768 × 512 GPU preview</option><option>1080p final render</option></select><label className="mt-4 block text-xs text-slate-500">Aspect ratio</label><select className="ghost mt-1 w-full rounded-xl p-3"><option>16:9 YouTube</option><option>9:16 Reels</option><option>1:1 Square</option></select></div><div className="card p-5"><h2 className="font-bold">Production pipeline</h2><p className="mt-3 text-sm text-slate-400">LTX is the active GPU engine. Generate short scenes first, then assemble them in Production Studio.</p><Link href="/studio" className="btn primary mt-4 block text-center">Open Production Studio</Link></div></aside></div></main>
}